eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
#    feign自带熔断器默认关闭
#feign:
#  hystrix:
#    enabled: true
